### ISSUE TITLE
Publish package to pypi?

### ISSUE THREAD

**Issue by Stedders** [coder-dojo-ham/coder-dojo-common-python#8]
Should we publish the package to pypi to ease installation?

**Comment by jonathancychow** [comment]
Yes definitely, the installation command is kind of long right now, with pypi hopefull we can make it much easier. I can look into it.

**Comment by jonathancychow** [comment]
I've published to pypi manually for now, going to look at [pypi-publish](https://github.com/marketplace/actions/pypi-publish) to automate the process.

**Comment by Stedders** [comment]
Works perfectly!

Good job @jonathancychow  👏🏻
